var firstTarget = document.getElementById("app");
var secondTarget = document.getElementsByTagName("p");
var thirdTarget = document.getElementsByClassName("para");
var forthTarget = document.querySelector("para");
var fifthTarget = document.querySelectorAll("para");
var childEl = document.getElementById("app");
console.log(firstTarget);
console.log(secondTarget);
console.log(thirdTarget);
console.log(forthTarget);
console.log(fifthTarget);
console.log(childEl.firstChild);
